package com.ep360.data.models;
// Generated Mar 16, 2015 10:37:31 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="cargo"
    ,catalog="voyage"
)
public class Cargo  implements java.io.Serializable {


     private Integer cargoId;
     private VoyHeader voyHeader;
     private String account;
     private String cargoName;
     private String loadingPort;
     private String dischargePort;
     private BigDecimal quantity;
     private BigDecimal frt;
     private BigDecimal term;
     private BigDecimal revenue;
     private BigDecimal addComm;
     private BigDecimal brkg;
     private BigDecimal frtTax;
     private BigDecimal linerTerm;

    public Cargo() {
    }

	
    public Cargo(VoyHeader voyHeader) {
        this.voyHeader = voyHeader;
    }
    public Cargo(VoyHeader voyHeader, String account, String cargoName, String loadingPort, String dischargePort, BigDecimal quantity, BigDecimal frt, BigDecimal term, BigDecimal revenue, BigDecimal addComm, BigDecimal brkg, BigDecimal frtTax, BigDecimal linerTerm) {
       this.voyHeader = voyHeader;
       this.account = account;
       this.cargoName = cargoName;
       this.loadingPort = loadingPort;
       this.dischargePort = dischargePort;
       this.quantity = quantity;
       this.frt = frt;
       this.term = term;
       this.revenue = revenue;
       this.addComm = addComm;
       this.brkg = brkg;
       this.frtTax = frtTax;
       this.linerTerm = linerTerm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cargo_id", unique=true, nullable=false)
    public Integer getCargoId() {
        return this.cargoId;
    }
    
    public void setCargoId(Integer cargoId) {
        this.cargoId = cargoId;
    }

@ManyToOne(cascade={CascadeType.PERSIST},fetch=FetchType.LAZY)
    @JoinColumn(name="voy_no")
    public VoyHeader getVoyHeader() {
        return this.voyHeader;
    }
    
    public void setVoyHeader(VoyHeader voyHeader) {
        this.voyHeader = voyHeader;
    }

    
    @Column(name="account", length=300)
    public String getAccount() {
        return this.account;
    }
    
    public void setAccount(String account) {
        this.account = account;
    }

    
    @Column(name="cargo_name", length=300)
    public String getCargoName() {
        return this.cargoName;
    }
    
    public void setCargoName(String cargoName) {
        this.cargoName = cargoName;
    }

    
    @Column(name="loading_port", length=300)
    public String getLoadingPort() {
        return this.loadingPort;
    }
    
    public void setLoadingPort(String loadingPort) {
        this.loadingPort = loadingPort;
    }

    
    @Column(name="discharge_port", length=300)
    public String getDischargePort() {
        return this.dischargePort;
    }
    
    public void setDischargePort(String dischargePort) {
        this.dischargePort = dischargePort;
    }

    
    @Column(name="quantity", precision=10)
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="frt", precision=10)
    public BigDecimal getFrt() {
        return this.frt;
    }
    
    public void setFrt(BigDecimal frt) {
        this.frt = frt;
    }

    
    @Column(name="term", precision=10)
    public BigDecimal getTerm() {
        return this.term;
    }
    
    public void setTerm(BigDecimal term) {
        this.term = term;
    }

    
    @Column(name="revenue", precision=10)
    public BigDecimal getRevenue() {
        return this.revenue;
    }
    
    public void setRevenue(BigDecimal revenue) {
        this.revenue = revenue;
    }

    
    @Column(name="add_comm", precision=10)
    public BigDecimal getAddComm() {
        return this.addComm;
    }
    
    public void setAddComm(BigDecimal addComm) {
        this.addComm = addComm;
    }

    
    @Column(name="brkg", precision=10)
    public BigDecimal getBrkg() {
        return this.brkg;
    }
    
    public void setBrkg(BigDecimal brkg) {
        this.brkg = brkg;
    }

    
    @Column(name="frt_tax", precision=10)
    public BigDecimal getFrtTax() {
        return this.frtTax;
    }
    
    public void setFrtTax(BigDecimal frtTax) {
        this.frtTax = frtTax;
    }

    
    @Column(name="liner_term", precision=10)
    public BigDecimal getLinerTerm() {
        return this.linerTerm;
    }
    
    public void setLinerTerm(BigDecimal linerTerm) {
        this.linerTerm = linerTerm;
    }




}


