package com.ep360.data.models;
// Generated Mar 16, 2015 10:37:31 PM by Hibernate Tools 4.3.1


import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PortRotation generated by hbm2java
 */
@Entity
@Table(name="port_rotation"
    ,catalog="voyage"
)
public class PortRotation  implements java.io.Serializable {


     private Integer portRotationId;
     private VoyHeader voyHeader;
     private String type;
     private String portName;
     private BigDecimal distance;
     private BigDecimal wf;
     private BigDecimal speed;
     private BigDecimal sea;
     private BigDecimal loadRate;
     private BigDecimal portIdleDays;
     private BigDecimal portWorkingDays;
     private BigDecimal demerages;
     private BigDecimal despatches;
     private BigDecimal portCharge;
     private Date arrivaleDate;
     private Date departureDate;

    public PortRotation() {
    }

	
    public PortRotation(VoyHeader voyHeader) {
        this.voyHeader = voyHeader;
    }
    public PortRotation(VoyHeader voyHeader, String type, String portName, BigDecimal distance, BigDecimal wf, BigDecimal speed, BigDecimal sea, BigDecimal loadRate, BigDecimal portIdleDays, BigDecimal portWorkingDays, BigDecimal demerages, BigDecimal despatches, BigDecimal portCharge, Date arrivaleDate, Date departureDate) {
       this.voyHeader = voyHeader;
       this.type = type;
       this.portName = portName;
       this.distance = distance;
       this.wf = wf;
       this.speed = speed;
       this.sea = sea;
       this.loadRate = loadRate;
       this.portIdleDays = portIdleDays;
       this.portWorkingDays = portWorkingDays;
       this.demerages = demerages;
       this.despatches = despatches;
       this.portCharge = portCharge;
       this.arrivaleDate = arrivaleDate;
       this.departureDate = departureDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="port_rotation_id", unique=true, nullable=false)
    public Integer getPortRotationId() {
        return this.portRotationId;
    }
    
    public void setPortRotationId(Integer portRotationId) {
        this.portRotationId = portRotationId;
    }

@ManyToOne(cascade={CascadeType.PERSIST},fetch=FetchType.LAZY)
    @JoinColumn(name="voy_no")
    public VoyHeader getVoyHeader() {
        return this.voyHeader;
    }
    
    public void setVoyHeader(VoyHeader voyHeader) {
        this.voyHeader = voyHeader;
    }

    
    @Column(name="type", length=40)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="port_name", length=300)
    public String getPortName() {
        return this.portName;
    }
    
    public void setPortName(String portName) {
        this.portName = portName;
    }

    
    @Column(name="distance", precision=10)
    public BigDecimal getDistance() {
        return this.distance;
    }
    
    public void setDistance(BigDecimal distance) {
        this.distance = distance;
    }

    
    @Column(name="wf", precision=10)
    public BigDecimal getWf() {
        return this.wf;
    }
    
    public void setWf(BigDecimal wf) {
        this.wf = wf;
    }

    
    @Column(name="speed", precision=10)
    public BigDecimal getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(BigDecimal speed) {
        this.speed = speed;
    }

    
    @Column(name="sea", precision=10)
    public BigDecimal getSea() {
        return this.sea;
    }
    
    public void setSea(BigDecimal sea) {
        this.sea = sea;
    }

    
    @Column(name="load_rate", precision=10)
    public BigDecimal getLoadRate() {
        return this.loadRate;
    }
    
    public void setLoadRate(BigDecimal loadRate) {
        this.loadRate = loadRate;
    }

    
    @Column(name="port_idle_days", precision=10)
    public BigDecimal getPortIdleDays() {
        return this.portIdleDays;
    }
    
    public void setPortIdleDays(BigDecimal portIdleDays) {
        this.portIdleDays = portIdleDays;
    }

    
    @Column(name="port_working_days", precision=10)
    public BigDecimal getPortWorkingDays() {
        return this.portWorkingDays;
    }
    
    public void setPortWorkingDays(BigDecimal portWorkingDays) {
        this.portWorkingDays = portWorkingDays;
    }

    
    @Column(name="demerages", precision=10)
    public BigDecimal getDemerages() {
        return this.demerages;
    }
    
    public void setDemerages(BigDecimal demerages) {
        this.demerages = demerages;
    }

    
    @Column(name="despatches", precision=10)
    public BigDecimal getDespatches() {
        return this.despatches;
    }
    
    public void setDespatches(BigDecimal despatches) {
        this.despatches = despatches;
    }

    
    @Column(name="port_charge", precision=10)
    public BigDecimal getPortCharge() {
        return this.portCharge;
    }
    
    public void setPortCharge(BigDecimal portCharge) {
        this.portCharge = portCharge;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="arrivale_date", length=10)
    public Date getArrivaleDate() {
        return this.arrivaleDate;
    }
    
    public void setArrivaleDate(Date arrivaleDate) {
        this.arrivaleDate = arrivaleDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="departure_date", length=10)
    public Date getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }




}


