package com.ep360.data.models;
// Generated Mar 16, 2015 10:37:31 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VesselMaster generated by hbm2java
 */
@Entity
@Table(name="vessel_master"
    ,catalog="voyage"
    , uniqueConstraints = @UniqueConstraint(columnNames="vessel_name") 
)
public class VesselMaster  implements java.io.Serializable {


     private VesselMasterId id;
     private Float laycan;
     private Float dwt;
     private String draft;
     private Float ballast;
     private Float laden;
     private String doDieselType;
     private Float doSea;
     private Float doIdle;
     private Float doWork;
     private String lsdoDieselType;
     private Float lsdoSea;
     private Float lsdoIdle;
     private Float lsdoWork;
     private Float foType;
     private Float foBallast;
     private Float foLaden;
     private Float foIdle;
     private Float foWork;
     private Float lsfoType;
     private Float lsfoBallast;
     private Float lsfoLaden;
     private Float lsfoIdle;
     private Float lsfoWork;

    public VesselMaster() {
    }

	
    public VesselMaster(VesselMasterId id) {
        this.id = id;
    }
    public VesselMaster(VesselMasterId id, Float laycan, Float dwt, String draft, Float ballast, Float laden, String doDieselType, Float doSea, Float doIdle, Float doWork, String lsdoDieselType, Float lsdoSea, Float lsdoIdle, Float lsdoWork, Float foType, Float foBallast, Float foLaden, Float foIdle, Float foWork, Float lsfoType, Float lsfoBallast, Float lsfoLaden, Float lsfoIdle, Float lsfoWork) {
       this.id = id;
       this.laycan = laycan;
       this.dwt = dwt;
       this.draft = draft;
       this.ballast = ballast;
       this.laden = laden;
       this.doDieselType = doDieselType;
       this.doSea = doSea;
       this.doIdle = doIdle;
       this.doWork = doWork;
       this.lsdoDieselType = lsdoDieselType;
       this.lsdoSea = lsdoSea;
       this.lsdoIdle = lsdoIdle;
       this.lsdoWork = lsdoWork;
       this.foType = foType;
       this.foBallast = foBallast;
       this.foLaden = foLaden;
       this.foIdle = foIdle;
       this.foWork = foWork;
       this.lsfoType = lsfoType;
       this.lsfoBallast = lsfoBallast;
       this.lsfoLaden = lsfoLaden;
       this.lsfoIdle = lsfoIdle;
       this.lsfoWork = lsfoWork;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vesselName", column=@Column(name="vessel_name", unique=true, nullable=false, length=100) ), 
        @AttributeOverride(name="vesselType", column=@Column(name="vessel_type", nullable=false, length=10) ) } )
    public VesselMasterId getId() {
        return this.id;
    }
    
    public void setId(VesselMasterId id) {
        this.id = id;
    }

    
    @Column(name="laycan", precision=12, scale=0)
    public Float getLaycan() {
        return this.laycan;
    }
    
    public void setLaycan(Float laycan) {
        this.laycan = laycan;
    }

    
    @Column(name="dwt", precision=10)
    public Float getDwt() {
        return this.dwt;
    }
    
    public void setDwt(Float dwt) {
        this.dwt = dwt;
    }

    
    @Column(name="draft", length=30)
    public String getDraft() {
        return this.draft;
    }
    
    public void setDraft(String draft) {
        this.draft = draft;
    }

    
    @Column(name="ballast", precision=12, scale=0)
    public Float getBallast() {
        return this.ballast;
    }
    
    public void setBallast(Float ballast) {
        this.ballast = ballast;
    }

    
    @Column(name="laden", precision=12, scale=0)
    public Float getLaden() {
        return this.laden;
    }
    
    public void setLaden(Float laden) {
        this.laden = laden;
    }

    
    @Column(name="do_diesel_type", length=10)
    public String getDoDieselType() {
        return this.doDieselType;
    }
    
    public void setDoDieselType(String doDieselType) {
        this.doDieselType = doDieselType;
    }

    
    @Column(name="do_sea", precision=12, scale=0)
    public Float getDoSea() {
        return this.doSea;
    }
    
    public void setDoSea(Float doSea) {
        this.doSea = doSea;
    }

    
    @Column(name="do_idle", precision=12, scale=0)
    public Float getDoIdle() {
        return this.doIdle;
    }
    
    public void setDoIdle(Float doIdle) {
        this.doIdle = doIdle;
    }

    
    @Column(name="do_work", precision=12, scale=0)
    public Float getDoWork() {
        return this.doWork;
    }
    
    public void setDoWork(Float doWork) {
        this.doWork = doWork;
    }

    
    @Column(name="lsdo_diesel_type", length=10)
    public String getLsdoDieselType() {
        return this.lsdoDieselType;
    }
    
    public void setLsdoDieselType(String lsdoDieselType) {
        this.lsdoDieselType = lsdoDieselType;
    }

    
    @Column(name="lsdo_sea", precision=12, scale=0)
    public Float getLsdoSea() {
        return this.lsdoSea;
    }
    
    public void setLsdoSea(Float lsdoSea) {
        this.lsdoSea = lsdoSea;
    }

    
    @Column(name="lsdo_idle", precision=12, scale=0)
    public Float getLsdoIdle() {
        return this.lsdoIdle;
    }
    
    public void setLsdoIdle(Float lsdoIdle) {
        this.lsdoIdle = lsdoIdle;
    }

    
    @Column(name="lsdo_work", precision=12, scale=0)
    public Float getLsdoWork() {
        return this.lsdoWork;
    }
    
    public void setLsdoWork(Float lsdoWork) {
        this.lsdoWork = lsdoWork;
    }

    
    @Column(name="fo_type", precision=12, scale=0)
    public Float getFoType() {
        return this.foType;
    }
    
    public void setFoType(Float foType) {
        this.foType = foType;
    }

    
    @Column(name="fo_ballast", precision=12, scale=0)
    public Float getFoBallast() {
        return this.foBallast;
    }
    
    public void setFoBallast(Float foBallast) {
        this.foBallast = foBallast;
    }

    
    @Column(name="fo_laden", precision=12, scale=0)
    public Float getFoLaden() {
        return this.foLaden;
    }
    
    public void setFoLaden(Float foLaden) {
        this.foLaden = foLaden;
    }

    
    @Column(name="fo_idle", precision=12, scale=0)
    public Float getFoIdle() {
        return this.foIdle;
    }
    
    public void setFoIdle(Float foIdle) {
        this.foIdle = foIdle;
    }

    
    @Column(name="fo_work", precision=12, scale=0)
    public Float getFoWork() {
        return this.foWork;
    }
    
    public void setFoWork(Float foWork) {
        this.foWork = foWork;
    }

    
    @Column(name="lsfo_type", precision=12, scale=0)
    public Float getLsfoType() {
        return this.lsfoType;
    }
    
    public void setLsfoType(Float lsfoType) {
        this.lsfoType = lsfoType;
    }

    
    @Column(name="lsfo_ballast", precision=12, scale=0)
    public Float getLsfoBallast() {
        return this.lsfoBallast;
    }
    
    public void setLsfoBallast(Float lsfoBallast) {
        this.lsfoBallast = lsfoBallast;
    }

    
    @Column(name="lsfo_laden", precision=12, scale=0)
    public Float getLsfoLaden() {
        return this.lsfoLaden;
    }
    
    public void setLsfoLaden(Float lsfoLaden) {
        this.lsfoLaden = lsfoLaden;
    }

    
    @Column(name="lsfo_idle", precision=12, scale=0)
    public Float getLsfoIdle() {
        return this.lsfoIdle;
    }
    
    public void setLsfoIdle(Float lsfoIdle) {
        this.lsfoIdle = lsfoIdle;
    }

    
    @Column(name="lsfo_work", precision=12, scale=0)
    public Float getLsfoWork() {
        return this.lsfoWork;
    }
    
    public void setLsfoWork(Float lsfoWork) {
        this.lsfoWork = lsfoWork;
    }




}


