package com.ep360.data.models;
// Generated Apr 2, 2015 11:37:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VesselGear generated by hbm2java
 */
@Entity
@Table(name="vessel_gear"
    ,catalog="voyage"
    , uniqueConstraints = @UniqueConstraint(columnNames="vessel_master_id") 
)
public class VesselGear  implements java.io.Serializable {


     private Integer vesselGearId;
     private VesselMaster vesselMaster;
     private String gear;
     private Double weightMt;
     private Double weightEa;
     private String gearType;

    public VesselGear() {
    }

    public VesselGear(VesselMaster vesselMaster, String gear, Double weightMt, Double weightEa, String gearType) {
       this.vesselMaster = vesselMaster;
       this.gear = gear;
       this.weightMt = weightMt;
       this.weightEa = weightEa;
       this.gearType = gearType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vessel_gear_id", unique=true, nullable=false)
    public Integer getVesselGearId() {
        return this.vesselGearId;
    }
    
    public void setVesselGearId(Integer vesselGearId) {
        this.vesselGearId = vesselGearId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vessel_master_id", unique=true)
    public VesselMaster getVesselMaster() {
        return this.vesselMaster;
    }
    
    public void setVesselMaster(VesselMaster vesselMaster) {
        this.vesselMaster = vesselMaster;
    }

    
    @Column(name="gear", length=100)
    public String getGear() {
        return this.gear;
    }
    
    public void setGear(String gear) {
        this.gear = gear;
    }

    
    @Column(name="weight_mt", precision=22, scale=0)
    public Double getWeightMt() {
        return this.weightMt;
    }
    
    public void setWeightMt(Double weightMt) {
        this.weightMt = weightMt;
    }

    
    @Column(name="weight_ea", precision=22, scale=0)
    public Double getWeightEa() {
        return this.weightEa;
    }
    
    public void setWeightEa(Double weightEa) {
        this.weightEa = weightEa;
    }

    
    @Column(name="gear_type", length=100)
    public String getGearType() {
        return this.gearType;
    }
    
    public void setGearType(String gearType) {
        this.gearType = gearType;
    }




}


