package com.ep360.data.models;
// Generated Apr 2, 2015 11:37:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * VesselHoldCapacity generated by hbm2java
 */
@Entity
@Table(name="vessel_hold_capacity"
    ,catalog="voyage"
    , uniqueConstraints = @UniqueConstraint(columnNames="vessel_master_id") 
)
public class VesselHoldCapacity  implements java.io.Serializable {


     private Integer vesselHoldCapacityId;
     private VesselMaster vesselMaster;
     private Double grain;
     private Double bale;

    public VesselHoldCapacity() {
    }

    public VesselHoldCapacity(VesselMaster vesselMaster, Double grain, Double bale) {
       this.vesselMaster = vesselMaster;
       this.grain = grain;
       this.bale = bale;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vessel_hold_capacity_id", unique=true, nullable=false)
    public Integer getVesselHoldCapacityId() {
        return this.vesselHoldCapacityId;
    }
    
    public void setVesselHoldCapacityId(Integer vesselHoldCapacityId) {
        this.vesselHoldCapacityId = vesselHoldCapacityId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vessel_master_id", unique=true)
    public VesselMaster getVesselMaster() {
        return this.vesselMaster;
    }
    
    public void setVesselMaster(VesselMaster vesselMaster) {
        this.vesselMaster = vesselMaster;
    }

    
    @Column(name="grain", precision=22, scale=0)
    public Double getGrain() {
        return this.grain;
    }
    
    public void setGrain(Double grain) {
        this.grain = grain;
    }

    
    @Column(name="bale", precision=22, scale=0)
    public Double getBale() {
        return this.bale;
    }
    
    public void setBale(Double bale) {
        this.bale = bale;
    }




}


