package com.ep360.data.models;
// Generated Mar 26, 2015 9:51:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VoyageVessel generated by hbm2java
 */
@Entity
@Table(name="voyage_vessel"
    ,catalog="voyage"
)
public class VoyageVessel  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -2400020044150959007L;
	private Integer voyageVesselId;
     private VoyHeader voyHeader;
     private String vesselName;
     private Double laycan;
     private String vesselType;
     private Double dwt;
     private String draft;
     private Double ballast;
     private Double laden;
     private String doDieselType;
     private Double doSea;
     private Double doIdle;
     private Double doWork;
     private String lsdoDieselType;
     private Double lsdoSea;
     private Double lsdoIdle;
     private Double lsdoWork;
     private Double foType;
     private Double foBallast;
     private Double foLaden;
     private Double foIdle;
     private Double foWork;
     private Double lsfoType;
     private Double lsfoBallast;
     private Double lsfoLaden;
     private Double lsfoIdle;
     private Double lsfoWork;

    public VoyageVessel() {
    }

    public VoyageVessel(VoyHeader voyHeader, String vesselName, Double laycan, String vesselType, Double dwt, String draft, Double ballast, Double laden, String doDieselType, Double doSea, Double doIdle, Double doWork, String lsdoDieselType, Double lsdoSea, Double lsdoIdle, Double lsdoWork, Double foType, Double foBallast, Double foLaden, Double foIdle, Double foWork, Double lsfoType, Double lsfoBallast, Double lsfoLaden, Double lsfoIdle, Double lsfoWork) {
       this.voyHeader = voyHeader;
       this.vesselName = vesselName;
       this.laycan = laycan;
       this.vesselType = vesselType;
       this.dwt = dwt;
       this.draft = draft;
       this.ballast = ballast;
       this.laden = laden;
       this.doDieselType = doDieselType;
       this.doSea = doSea;
       this.doIdle = doIdle;
       this.doWork = doWork;
       this.lsdoDieselType = lsdoDieselType;
       this.lsdoSea = lsdoSea;
       this.lsdoIdle = lsdoIdle;
       this.lsdoWork = lsdoWork;
       this.foType = foType;
       this.foBallast = foBallast;
       this.foLaden = foLaden;
       this.foIdle = foIdle;
       this.foWork = foWork;
       this.lsfoType = lsfoType;
       this.lsfoBallast = lsfoBallast;
       this.lsfoLaden = lsfoLaden;
       this.lsfoIdle = lsfoIdle;
       this.lsfoWork = lsfoWork;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="voyage_vessel_id", unique=true, nullable=false)
    public Integer getVoyageVesselId() {
        return this.voyageVesselId;
    }
    
    public void setVoyageVesselId(Integer voyageVesselId) {
        this.voyageVesselId = voyageVesselId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="voy_no")
    public VoyHeader getVoyHeader() {
        return this.voyHeader;
    }
    
    public void setVoyHeader(VoyHeader voyHeader) {
        this.voyHeader = voyHeader;
    }

    
    @Column(name="vessel_name", length=100)
    public String getVesselName() {
        return this.vesselName;
    }
    
    public void setVesselName(String vesselName) {
        this.vesselName = vesselName;
    }

    
    @Column(name="laycan", precision=12, scale=0)
    public Double getLaycan() {
        return this.laycan;
    }
    
    public void setLaycan(Double laycan) {
        this.laycan = laycan;
    }

    
    @Column(name="vessel_type", length=10)
    public String getVesselType() {
        return this.vesselType;
    }
    
    public void setVesselType(String vesselType) {
        this.vesselType = vesselType;
    }

    
    @Column(name="dwt", precision=10)
    public Double getDwt() {
        return this.dwt;
    }
    
    public void setDwt(Double dwt) {
        this.dwt = dwt;
    }

    
    @Column(name="draft", length=30)
    public String getDraft() {
        return this.draft;
    }
    
    public void setDraft(String draft) {
        this.draft = draft;
    }

    
    @Column(name="ballast", precision=12, scale=0)
    public Double getBallast() {
        return this.ballast;
    }
    
    public void setBallast(Double ballast) {
        this.ballast = ballast;
    }

    
    @Column(name="laden", precision=12, scale=0)
    public Double getLaden() {
        return this.laden;
    }
    
    public void setLaden(Double laden) {
        this.laden = laden;
    }

    
    @Column(name="do_diesel_type", length=10)
    public String getDoDieselType() {
        return this.doDieselType;
    }
    
    public void setDoDieselType(String doDieselType) {
        this.doDieselType = doDieselType;
    }

    
    @Column(name="do_sea", precision=12, scale=0)
    public Double getDoSea() {
        return this.doSea;
    }
    
    public void setDoSea(Double doSea) {
        this.doSea = doSea;
    }

    
    @Column(name="do_idle", precision=12, scale=0)
    public Double getDoIdle() {
        return this.doIdle;
    }
    
    public void setDoIdle(Double doIdle) {
        this.doIdle = doIdle;
    }

    
    @Column(name="do_work", precision=12, scale=0)
    public Double getDoWork() {
        return this.doWork;
    }
    
    public void setDoWork(Double doWork) {
        this.doWork = doWork;
    }

    
    @Column(name="lsdo_diesel_type", length=10)
    public String getLsdoDieselType() {
        return this.lsdoDieselType;
    }
    
    public void setLsdoDieselType(String lsdoDieselType) {
        this.lsdoDieselType = lsdoDieselType;
    }

    
    @Column(name="lsdo_sea", precision=12, scale=0)
    public Double getLsdoSea() {
        return this.lsdoSea;
    }
    
    public void setLsdoSea(Double lsdoSea) {
        this.lsdoSea = lsdoSea;
    }

    
    @Column(name="lsdo_idle", precision=12, scale=0)
    public Double getLsdoIdle() {
        return this.lsdoIdle;
    }
    
    public void setLsdoIdle(Double lsdoIdle) {
        this.lsdoIdle = lsdoIdle;
    }

    
    @Column(name="lsdo_work", precision=12, scale=0)
    public Double getLsdoWork() {
        return this.lsdoWork;
    }
    
    public void setLsdoWork(Double lsdoWork) {
        this.lsdoWork = lsdoWork;
    }

    
    @Column(name="fo_type", precision=12, scale=0)
    public Double getFoType() {
        return this.foType;
    }
    
    public void setFoType(Double foType) {
        this.foType = foType;
    }

    
    @Column(name="fo_ballast", precision=12, scale=0)
    public Double getFoBallast() {
        return this.foBallast;
    }
    
    public void setFoBallast(Double foBallast) {
        this.foBallast = foBallast;
    }

    
    @Column(name="fo_laden", precision=12, scale=0)
    public Double getFoLaden() {
        return this.foLaden;
    }
    
    public void setFoLaden(Double foLaden) {
        this.foLaden = foLaden;
    }

    
    @Column(name="fo_idle", precision=12, scale=0)
    public Double getFoIdle() {
        return this.foIdle;
    }
    
    public void setFoIdle(Double foIdle) {
        this.foIdle = foIdle;
    }

    
    @Column(name="fo_work", precision=12, scale=0)
    public Double getFoWork() {
        return this.foWork;
    }
    
    public void setFoWork(Double foWork) {
        this.foWork = foWork;
    }

    
    @Column(name="lsfo_type", precision=12, scale=0)
    public Double getLsfoType() {
        return this.lsfoType;
    }
    
    public void setLsfoType(Double lsfoType) {
        this.lsfoType = lsfoType;
    }

    
    @Column(name="lsfo_ballast", precision=12, scale=0)
    public Double getLsfoBallast() {
        return this.lsfoBallast;
    }
    
    public void setLsfoBallast(Double lsfoBallast) {
        this.lsfoBallast = lsfoBallast;
    }

    
    @Column(name="lsfo_laden", precision=12, scale=0)
    public Double getLsfoLaden() {
        return this.lsfoLaden;
    }
    
    public void setLsfoLaden(Double lsfoLaden) {
        this.lsfoLaden = lsfoLaden;
    }

    
    @Column(name="lsfo_idle", precision=12, scale=0)
    public Double getLsfoIdle() {
        return this.lsfoIdle;
    }
    
    public void setLsfoIdle(Double lsfoIdle) {
        this.lsfoIdle = lsfoIdle;
    }

    
    @Column(name="lsfo_work", precision=12, scale=0)
    public Double getLsfoWork() {
        return this.lsfoWork;
    }
    
    public void setLsfoWork(Double lsfoWork) {
        this.lsfoWork = lsfoWork;
    }




}


